### PR TITLE
feat: store request url in HttpError

### PR DESCRIPTION
**Pull request by jviotti**
Very helpful for debugging purposes. I'm getting various
`HttpError` instances, and its very hard to understand the reason
without knowing what resource you are requesting.

Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

### CODE REVIEW

**Comment by jviotti** [comment]
Looks like Travis CI finished successfully, but didn't update the PR status flag

**Comment by gr2m** [comment]
It should already be set on `error.request.url`. Here is a code snippet showing it:
https://runkit.com/gr2m/octokit-request-js-26/1.0.0

I’ve mention it in the docs:

image

Maybe there is a way to make it more clear? Or is there something else that you are missing?

**Comment by jviotti** [comment]
@gr2m Hm, its interesting that `.request` is not defined for me, which might explain why it fails. This is what I see on my logs:

```
{
  "name": "HttpError",
  "message": "Not Found",
  "stack": "HttpError: Not Foundn at response.text.then.message (/usr/src/app/node_modules/@octokit/request/lib/request.js:55:27)n at process._tickCallback (internal/process/next_tick.js:68:7)",
  "status": 404,
  "headers": {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
    "connection": "close",
    "content-encoding": "gzip",
    "content-security-policy": "default-src 'none'",
    "content-type": "application/json; charset=utf-8",
    "date": "Tue, 08 Jan 2019 17:27:14 GMT",
    "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
    "server": "GitHub.com",
    "status": "404 Not Found",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "transfer-encoding": "chunked",
    "x-accepted-oauth-scopes": "",
    "x-content-type-options": "nosniff",
    "x-frame-options": "deny",
    "x-github-media-type": "github.v3; format=json",
    "x-github-request-id": "6D99:0C7A:1196070:165D0CC:5C34DD72",
    "x-oauth-scopes": "admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user, write:discussion",
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4999",
    "x-ratelimit-reset": "1546972034",
    "x-xss-protection": "1; mode=block"
  },
  "documentation_url": "https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue"
}
```

**Comment by jviotti** [comment]
I also don't understand how `documentation_url` ends up in the top level of the error object?

**Comment by jviotti** [comment]
Ah, I think I'm not running a recent version of this module. This is how `HttpError` looks like in `node_modules`:

```js
module.exports = class HttpError extends Error {
  constructor (message, statusCode, headers) {
    super(message)

    // Maintains proper stack trace (only available on V8)
    /* istanbul ignore next */
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, this.constructor)
    }

    this.name = 'HttpError'
    this.status = statusCode
    Object.defineProperty(this, 'code', {
      get () {
        console.warn('`error.code` is deprecated, use `error.status`.')
        return statusCode
      }
    })
    this.headers = headers
  }
}
```

I updated the files inside `node_modules`, created a diff, applied it to the latest master, blindly fixed conflicts, and sent the PR, so I missed the whole thing :D

Thanks a lot anyways, I'll close the PR then!

**Comment by gr2m** [comment]
Glad that you got it working :)

**Pull request closed without merging**
