### PR TITLE
fix: iterate through response headers correctly 

### PR DESCRIPTION
**Pull request by jviotti**
Otherwise we get the following error:

```
HttpError: response.headers.entries(...) is not a function or its return value is not iterable
```

Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

### CODE REVIEW

**Comment by jviotti** [comment]
Hm, I guess older JavaScript versions don't have `Object.entries()`, but they don't have `.entries()` either. I'll try to come up with a more compatible alternative.

**Comment by jviotti** [comment]
OK, so in this context, `.entries()` is indeed valid (taking a look at `node-fetch`). I'm not sure why I get this error though, and I can only reproduce on CI, which makes it harder to debug :/

**Comment by jviotti** [comment]
Alright, so when there are no response headers, then `.entries()` seems to return `undefined`. This is how my request looks like:

```json
{
  "method": "POST",
  "url": "https://api.github.com/repos/balena-io/jellyfish-test-github/issues",
  "headers": {
    "accept": "application/vnd.github.v3+json",
    "user-agent": "jellyfish v10.0.4 octokit.js/16.0.1 Node.js/9.11.2 (macOS Mojave; x64)",
    "authorization": "token XXXXXXXXXXXXXXXXXXXXX",
    "content-type": "application/json; charset=utf-8"
  },
  "body": "{\"title\":\"Test Issue iIleYq7BevFlo8dS5slaWH14vvw4CmFk\",\"body\":\"[fugdzbkhzxt4ffvo23a0zej0k8vmxnp4] Issue body\",\"labels\":[]}",
  "request": {
    "validate": {
      "assignee": {
        "type": "string"
      },
      "assignees": {
        "type": "string[]"
      },
      "body": {
        "type": "string"
      },
      "labels": {
        "type": "string[]"
      },
      "milestone": {
        "type": "integer"
      },
      "owner": {
        "required": true,
        "type": "string"
      },
      "repo": {
        "required": true,
        "type": "string"
      },
      "title": {
        "required": true,
        "type": "string"
      }
    }
  }
}
```

**Comment by jviotti** [comment]
I do see some response headers if I print the object, but I don't understand why the call to `.entries()` fail

**Comment by jviotti** [comment]
I added a check to ensure `response.headers.entries` exists before calling it and tests run fine locally, but to be honest I have non idea why its not available, nor I can reliably reproduce in order to write a test case. Ideas?

**Comment by gr2m** [comment]
> Alright, so when there are no response headers, then .entries() seems to return undefined

All responses from GitHub have response headers. It must be sth else 🤔 

> response.headers.entries is not a function

Where do you see that error? If it’s node, what version? If it’s in a browser, which one and what version?

**Comment by gr2m** [comment]
Thanks @pvdlg!

@jviotti A new version is out that has the `node-fetch` dependency, can you please try to reproduce the issue?

**Comment by jviotti** [comment]
Thanks a lot @gr2m @pvdlg ! I'm closing this as @LucianBuzzo found and fixed the root cause!

**Comment by jviotti** [comment]
@gr2m BTW my actual issue was that since `node-fetch` was not declared in the `package.json`, then one of the instances of this module was requiring a very old `node-fetch` version brought by another unrelated package. That old version doesn't have `.entries()` on the headers data structure.

**Pull request closed without merging**
