### PR TITLE
feat: add `redirect` request option

### LINKED ISSUE #635: [BUG]: Redirect option is not passed through...
### What happened?

Seems to be:
#611

which in theory was fixed by #612 but #612 seems to be missing any code that actually passes the redirect through, only removes it as an option on the primary object.

What is interesting is this used to work (not sure if after #612 )  https://github.com/octokit/octokit.js/issues/1999 but I didn't bisect to figure out what changes stopped it from doing so.

While I could be missing something it looks like we manually build the fetch object, so I don't see how this option would be properly set other than with specifying it (see PR for this).

This specifically breaks the situation where you want to get the download URL for an artifact but not actually download it.

### Versions

Octokit/request 8.1.1

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mitchcapper**
Resolves #635

----

### Before the change?

* Setting {request: {redirect:"value"} } does nothing

### After the change?

* Setting the redirect property on the request sub property is properly passed to fetch for the request.

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Is it breaking? not really, this is the desired behavior, I can't imagine anyone has a valid use case to set the redirect option and have it ignored.

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [X] No

----

### CODE REVIEW

**Review by gr2m — CHANGES_REQUESTED** [review]
Could you add a test please, to avoid a future regression?

**Comment by wolfy1339** [comment]
The option was removed in #599 / #612 

We removed all custom options, in favour of users using wrapping fetch with their options

Do we want to reintroduce it though? @gr2m

**Comment by gr2m** [comment]
It's not a custom option though? I'm not quite sure if we discussed removing the `redirect` option explicitly, I thought that's one we wanted to keep passing through?

**Comment by mitchcapper** [comment]
After discussion in #635 I did think this was the desired current behavior so meant to close this PR.   I am happy to add a test case to ensure this option works if it is desired for this feature to be re-introduced.

**Comment by gr2m** [comment]
@wolfy1339 can you recall specifically why we removed the `redirect` option, given that it's a native `fetch` option? It might be related to the fact that (I think) it behaves differently in browsers and backend environments due to CORS restrictions that only apply in browsers?

**Comment by wolfy1339** [comment]
I don't know.

**Comment by gr2m** [comment]
It's odd to me that we left `signal` but removed `request`. 

I think for now I would leave it as is as we have a working workaround. We can revisit the discussion as more folks experience the lack of `redirect` and other native fetch options as friction

**Comment by wolfy1339** [comment]
Requires https://github.com/octokit/types.ts/pull/630

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
