### PR TITLE
Convert project to typescript

### PR DESCRIPTION
**Pull request by wolfy1339**
Had this lying around, and now that `@octokit/endpoint` was converted, this is the next one down the pipe

### Todos

Resolve as part of this PR or make follow up issues

- [x] ~~remove duplication with types from `@octokit/endpoint`~~ #54
- [x] ~~add browser tests back. Instead of running all tests, make separate tests which only test the basics, as jest is not compatible with Cypress~~ #55
- [x] ~~add generated types for `request(route, parameters)`~~ #56

### CODE REVIEW

**Comment by wolfy1339** [comment]
@gr2m I've mostly finished this, now would be the time you come by and fix the remainder of the wrnings with your knowledge of the codebase

**Comment by gr2m** [comment]
see my changes at https://github.com/octokit/endpoint.js/pull/47 introducing pika for building / direct import for modern browsers from https://unpkg.com/

I’ll work on typescript definitions for all endpoints, at least for the `endpoint(route, options)` interface, I’d like to add the same to `@octokit/request`, but we can do that in a follow up PR

**Comment by wolfy1339** [comment]
pika should be in another PR. Since it's not ready yet and depends on upstream to push a patch

**Comment by gr2m** [comment]
As you prefer 👍 

I don’t mind adding the patch as I did in `@octokit/endpoint.js` until upstream is resolved

**Comment by gr2m** [comment]
> pika should be in another PR. Since it's not ready yet and depends on upstream to push a patch

It’s been fixed upstream, you can copy the setup of endpoint.js.

I also finished the generated types via https://github.com/octokit/endpoint.js/pull/53, I want to add that to `@octokit/request` as well, but we can do a follow up PR for that. Maybe we can reuse the options types

**Comment by wolfy1339** [comment]
I'm going to mark this as ready for review, so that CI can run and merge conflicts appear

**Comment by wolfy1339** [comment]
@gr2m I'm going to need your help with the right types and all. Tests are all broken because of this :/

**Comment by gr2m** [comment]
I’m looking into it :)

**Comment by gr2m** [comment]
Some of it got resolved by moving to `@pika/pack`. Do you mind if I adapt the setup to what we now have with `@octokit/endpoint`?

**Comment by wolfy1339** [comment]
No problem, that was something else I was going to do once I had things working properly

**Comment by gr2m** [comment]
@wolfy1339 I think this is good to go? I’ve added a few TODOs to the pull request description, but we can make follow up issues for these and iterate

**Comment by wolfy1339** [comment]
Looks fine and dandy

**Comment by gr2m** [comment]
`@octokit/rest` is currently using internal APIs
https://github.com/octokit/rest.js/blob/7601bd78c449bf33c2058ce94e2ef3e7d3106c9c/lib/request-with-defaults.js#L3

I can think of two ways to address this

1. Export `fetchWrapper`, which is what `lib/request` used to export
2. Move the requestWithHook logic into `@octokit/request`, maybe as a  secondary export?

   ```js
    import { requestWithHook } from '@octokit/request'
    ```

The 1st option is simpler to implement and would be the same as things are today. I would not document it and continue to consider it to be usage of internal APIs which might break at any update.

The 2nd option is more elegant and would have the added benefit that we would no longer need to pin `@octokit/request` version 🤔 

I’ll see how much of an effort the 2nd option will be, if I can’t figure it out tonight I’ll go with the 1st option and make a follow up issue

**Comment by gr2m** [comment]
Adds a few kb, but adds lots of interesting possibilities

image

Any thoughts? I’ll sleep over it

**Pull request merged**
